apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "wombo-combo.fullname" . }}-ingress
  namespace: {{ include "wombo-combo.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.annotations.ingressclass }}"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.annotations.clusterIssuer }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.rules.clientPath }}
            backend:
              serviceName: {{ .Values.service.client.name }}
              servicePort: {{ .Values.service.client.ports.port }}
          - path: {{ .Values.ingress.rules.serverPath }}
            backend:
              serviceName: {{ .Values.service.server.name }}
              servicePort: {{ .Values.service.server.ports.port }}