apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- .Values.ingress.annotations . | nindent 4 }}
spec:
  tls:
  - hosts:
    - sykesdev.ca
    secretName: letsencrypt-prod
  rules:
    http:
        paths:
          - path: {{ .Values.ingress.rules.path }}
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.ingress.rules.servicePort }}