# Values for resume-website/client chart
# By: Benjamin Sykes

# DEPLOYMENT VALUES
namespace: resume-website-namespace
labels: 
  app: resume-site-client
replicaCount: 1

image:
  repository: sykeben/resume-client
  # tag: latest
restartPolicy: Always
port: 3000

resources:
  limits:
    cpu: 100m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 128Mi

# SERVICE VALUES
service:
  name: resume-client-cluster-ip
  labels: 
    svc: resume-site-client
  type: ClusterIP
  ports:
    name: client-http-port
    port: 80
    targetPort: 3000

# INGRESS
ingress:
  name: ingress-resume-client
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  rules:
    path: /
    servicePort: 3000