# Values for resume-website/client chart
# By: Benjamin Sykes

# DEPLOYMENT VALUES
namespace: resume-website-namespace
labels: 
  app: resume-site-server
replicaCount: 1

image:
  repository: sykeben/resume-server
  # tag: latest
  env:
    email:
      to: ben@sykesdev.ca
      from: ben@sykesdev.ca
    secretName: resume-website-secret
restartPolicy: Always
port: 5000

resources:
  limits:
    cpu: 70m
    memory: 100Mi
  requests:
    cpu: 20m
    memory: 25Mi

# SERVICE VALUES
service:
  name: resume-server-cluster-ip
  labels: 
    svc: resume-site-server
  type: ClusterIP
  ports:
    name: server-http-port
    port: 5000
    targetPort: 5000

# INGRESS
ingress:
  name: ingress-resume-server
  tls:
    host: sykesdev.ca
    secretName: letsencrypt-prod
  annotations:
    ingressclass: nginx
    clusterissuer: letsencrypt-prod
  rules:
    path: /api
    servicePort: 5000