apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ include "gitbuilder-landing.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.annotations.ingressclass }}"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.annotations.clusterissuer }}"
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.tls.host }}"
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: "{{ .Values.ingress.tls.host }}"
      http:
        paths:
          - path: {{ .Values.ingress.rules.path }}
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.ingress.rules.servicePort }}