apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resume-website.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- .Values.labels . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- .Values.labels . | nindent 4 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        {{- .Values.labels . | nindent 4 }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ include "resume-website.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.port }}
          resources: {{ .Values.resources | nindent 12 }}